### ISSUE TITLE
what is the DeOldify.hmodel

### ISSUE THREAD

**Issue by srinivas68** [ColorfulSoft/DeOldify.NET#1]
hi good day. what is the .hmodel. i downloaded ColorizeArtistic_gen.pth from deoldify.  and renamed that file. exe file generated. working but no colour generated.. so what is the deOldify.hmodel... thanks

**Comment by GlebSBrykin** [comment]
Good afternoon, srinivas68!
DeOldify.hmodel are pure weights from ColorizeArtistic_gen.pth, preprocessed and compressed into the half data type to reduce the size. I want to draw your attention to the fact that DeOldify.hmodel is unstructured binary data that can only be read by the code that is published here, and the model from the original DeOldify repository is a file in the PyTorch format. They are incompatible with each other. You should download DeOldify.hmodel from releases, put it in src\Resources without renaming, and then run Compile.bat again.

**Comment by srinivas68** [comment]
thank you  (https://github.com/ColorfulSoft/DeOldify.NET/releases/download/Weights/DeOldify.hmodel) downloaded . working good little bit slow . great Thank you again
