### ISSUE TITLE
Add option to change model

### ISSUE THREAD

**Issue by MrShinyBoots** [ColorfulSoft/DeOldify.NET#17]
Deoldify lists that there are currently 2 models - artistic and stable - it would be nice to have an option to choose which model to use in your gui, many thanks

**Comment by GlebSBrykin** [comment]
> I tried to do this, but I ran into a problem: it required too much memory to perform coloring with stable weights.

It looks like this problem has been solved. A new convolution algorithm and memory allocation using a different function will solve this problem. Work on stable weights has begun.

_Originally posted by @GlebSBrykin in https://github.com/ColorfulSoft/DeOldify.NET/issues/13#issuecomment-1111362236_

**Comment by GlebSBrykin** [comment]
Done.
