### ISSUE TITLE
About CPU usage during use

### ISSUE THREAD

**Issue by whghjyh** [ColorfulSoft/DeOldify.NET#18]
In the process of running this program, I found that this program takes up a lot of CPU resources and causes stuttering, while the GPU (Nvidia) occupancy rate is very low.I wonder if this is because the program only supports calling the CPU without adapting the GPU, or if there is something wrong with my computer.

**Comment by GlebSBrykin** [comment]
Good afternoon! The program really works only on the CPU, so at 100% CPU load, the load on the graphics card will be zero. It doesn't depend on your computer's hardware or software.
