### ISSUE TITLE
dowload of 2.1

### ISSUE THREAD

**Issue by Excurl** [ColorfulSoft/DeOldify.NET#27]
where is release of 
""[10.09.2022] - Version 2.1 has been released. The ability to drag and drop images into the application has been added, error handling has been improved, and the process of saving the result has been simplified.""

**Comment by GlebSBrykin** [comment]
There is no binary release for this version. It is necessary to assemble the required assembly (Artistic/Stable, Float/Half, SIMD/notSIMD) yourself according to the instructions from the README.
