### ISSUE TITLE
video feature

### ISSUE THREAD

**Issue by Archviz360** [ColorfulSoft/DeOldify.NET#3]
Hello! could you add video feature ??

**Comment by GlebSBrykin** [comment]
Hello, Archvis360!
At the moment, there are no plans to add such a feature. Coloring a single frame, depending on its size and processing power of the processor, takes an average of 30-120 seconds. It is not difficult to calculate how long it will take to color one second of a video with a frame rate of 25. Moreover, the model proposed for video is more resource-intensive than the one used for photos and is presented here, so the process will be even slower and will require even more resources. However, in the future it is planned to create a special version of the application for .NET 5 and .NET Core, where it will be possible to speed up the process by using SIMD. Then, perhaps, video coloring support will be added.
Sincerely,
Gleb Brykin
