### ISSUE TITLE
problem with reconstruct color scheme

### ISSUE THREAD

**Issue by RoDanny2021** [ColorfulSoft/DeOldify.NET#30]
I tested the coloring for several pictures.They all failed.Apart from coloring the landscape, which is ok, as well as the people's skin, the rest have nothing to do with the original colors.
I think it would be useful to be able to have an eyedropper with which you can specify some colors/weddings from the picture to help the program restore them.

**Comment by GlebSBrykin** [comment]
DeOldify.NET - this is a DeOldify implementation for .NET Framework and Mono. There are no (and cannot be) functions not provided by DeOldify. DeOldify does not currently support manually specifying object colors. If you need such functionality, look towards "automatic colorization functionality for Real-Time User-Guided Image Colorization with Learned Deep Priors". Author proposed an implementation in PyTorch, which should be easy to run: https://github.com/richzhang/colorization
