### ISSUE TITLE
C# code clean-up

### ISSUE THREAD

**Issue by emilyseville7cfg** [ColorfulSoft/DeOldify.NET#4]
- code formatting
- small code optimisations

This issue can be assigned to me.

**Comment by GlebSBrykin** [comment]
Where exactly and what exactly needs to be optimized? And in which place exactly is the formatting not satisfied? Specific items will be considered.

**Comment by emilyseville7cfg** [comment]
Let's consider one specific file (DeOldify.cs):
- there are several empty lines (13 line for instance)
- many xml-comments missing <return> keyword  (21 line for instance)
- no one naming convention for methods, their parameters, variables and consts
- Initialize method is very long and unreadable

**Comment by GlebSBrykin** [comment]
> * there are several empty lines (13 line for instance)

If you are a little more careful, you will notice that there is one empty line between the declarations of methods, classes, structures, etc.

```C#
using System;

namespace Sample
{

  public static class Program
  {

    public static void Main()
    {
      Console.WriteLine("Hello, World!");
    }

  }

}
```



> * many xml-comments missing `<return>` keyword  (21 line for instance)

Is it so critical in the APP? This is an APPLICATION, not a class library.



> * `Initialize` method is very long and unreadable

This is an automatically generated method. It doesn't need to be read.



> * many magic numbers exist

I understand that we are talking about the same Initialize method. So these "magic" numbers are the sizes of tensors that need to be loaded from the stream. What kind of demystification do you want to see here? The same applies to the Colorize method. There, the numbers denote convolution parameters, such as stride, dilation, padding, and the number of groups. These numbers are determined by the architecture of the neural network and it is impossible in most cases to give a clear mathematical justification for why there is exactly 1 and not 2, for example. So the author of the architecture decided and it works.

I would like to emphasize, however, that we are talking about neural network code, and not about database or user interface code. There's a lot of magic here and that's fine.

**Comment by emilyseville7cfg** [comment]
> Is it so critical in the APP? This is an APPLICATION, not a class library.

So why to use xml comments at all if you don't use intellisence that can help you to discover your types and type member descriptions? If you use them it's a bad practise to miss some tags.

> This is an automatically generated method.

Where it is generated?
