### ISSUE TITLE
CI and CD setup

### ISSUE THREAD

**Issue by emilyseville7cfg** [ColorfulSoft/DeOldify.NET#5]
There are many code style inconsistency. CI will mandate you to avoid this problems. And CD can help automatic release deployment. Also I will train my skills in DevOps. :)

This issue also can be assigned to me.

**Comment by GlebSBrykin** [comment]
> Also I will train my skills in DevOps.

It's better to train on cats :) (C) Operation "Y" and other Shurik's adventures
