### ISSUE TITLE
Error start 

### ISSUE THREAD

**Issue by alexey267** [ColorfulSoft/DeOldify.NET#9]
This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

Sistem:
Windows 10
NET Framework 4.5

**Comment by emilyseville7cfg** [comment]
I agree, it would be very well if @GlebSBrykin update this project to NET 5.

**Comment by GlebSBrykin** [comment]
> This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

This is not an error, but a warning from the compiler. This should not prevent the exe from being built.

**Comment by GlebSBrykin** [comment]
> I agree, it would be very well if @GlebSBrykin update this project to NET 5. :)

In any case, it will be a separate branch that does not cancel or overlap the main one, which is intended for the built-in Windows dotnet.

**Comment by emilyseville7cfg** [comment]
> In any case, it will be a separate branch that does not cancel or overlap the main one, which is intended for the built-in Windows dotnet.

Maybe it's better to create another repo to this purpose. It allow you to support several project versions at the same time for both repos without messing up in a single repo.

**Comment by emilyseville7cfg** [comment]
@alexey267, I've [cloned](https://github.com/UI-Apps/mono-deoldify) this repo and I try to update project to .NET 5 in the future and add missing features at my glance. :)
